//Authentication
//Login
export const AUTHLOGIN_SUCCESS = 'AUTHLOGIN_SUCCESS';
export const AUTHLOGIN_ERROR = 'AUTHLOGIN_ERROR';
//Generate OTP
export const GENERATEEMAILOTP_SUCCESS = 'GENERATEEMAILOTP_SUCCESS';
export const GENERATEEMAILOTP_ERROR = 'GENERATEEMAILOTP_ERROR';
//Update Password
export const UPDATEPASSWORD_SUCCESS = 'UPDATEPASSWORD_SUCCESS';
export const UPDATEPASSWORD_ERROR = 'UPDATEPASSWORD_ERROR';

//Users
//Get All Users
export const ALLUSERS_LOADING = 'ALLUSERS_LOADING';
export const ALLUSERS_SUCCESS = 'ALLUSERS_SUCCESS';
export const ALLUSERS_ERROR = 'ALLUSERS_ERROR';
//User Types
export const ALLUSERTYPES_SUCCESS = 'ALLUSERTYPES_SUCCESS';
export const ALLUSERTYPES_ERROR = 'ALLUSERTYPES_ERROR';
//Add User
export const ADDUSER_SUCCESS = 'ADDUSER_SUCCESS';
export const ADDUSER_ERROR = 'ADDUSER_ERROR';
//Update User
export const UPDATEUSER_SUCCESS = 'UPDATEUSER_SUCCESS';
export const UPDATEUSER_ERROR = 'UPDATEUSER_ERROR';
//User Profile Upload
export const UPLOADUSERPROFILE_SUCCESS = 'UPLOADUSERPROFILE_SUCCESS';
export const UPLOADUSERPROFILE_ERROR = 'UPLOADUSERPROFILE_ERROR';

//Remove User
export const REMOVEUSER_SUCCESS = 'REMOVEUSER_SUCCESS';
export const REMOVEUSER_ERROR = 'REMOVEUSER_ERROR';

//Teams
//Get All Teams
export const ALLTEAMS_LOADING = 'ALLTEAMS_LOADING';
export const ALLTEAMS_SUCCESS = 'ALLTEAMS_SUCCESS';
export const ALLTEAMS_ERROR = 'ALLTEAMS_ERROR';
//Add Team
export const ADDTEAM_SUCCESS = 'ADDTEAM_SUCCESS';
export const ADDTEAM_ERROR = 'ADDTEAM_ERROR';
//Get All Players
export const ALLPLAYERS_SUCCESS = 'ALLPLAYERS_SUCCESS';
export const ALLPLAYERS_ERROR = 'ALLPLAYERS_ERROR';
//Add team Players
export const ADDTEAMPLAYERS_SUCCESS = 'ADDTEAMPLAYERS_SUCCESS';
export const ADDTEAMPLAYERS_ERROR = 'ADDTEAMPLAYERS_ERROR';

//Match
//Get All Matches
export const ALLMATCHES_LOADING = 'ALLMATCHES_LOADING';
export const ALLMATCHES_SUCCESS = 'ALLMATCHES_SUCCESS';
export const ALLMATCHES_ERROR = 'ALLMATCHES_ERROR';
//All Competition Types
export const ALLCOMPETITIONTYPES_SUCCESS = 'ALLCOMPETITIONTYPES_SUCCESS';
export const ALLCOMPETITIONTYPES_ERROR = 'ALLCOMPETITIONTYPES_ERROR';
//All Match Rules List
export const ALLMATCHRULESLIST_SUCCESS = 'ALLMATCHRULESLIST_SUCCESS';
export const ALLMATCHRULESLIST_ERROR = 'ALLMATCHRULESLIST_ERROR';
//Add Match
export const ADDMATCH_SUCCESS = 'ADDMATCH_SUCCESS';
export const ADDMATCH_ERROR = 'ADDMATCH_ERROR';
//Add Match Rule
export const ADDMATCHRULE_SUCCESS = 'ADDMATCHRULE_SUCCESS';
export const ADDMATCHRULE_ERROR = 'ADDMATCHRULE_ERROR';

//Get All Countries
export const ALLCOUNTRIES_SUCCESS = 'ALLCOUNTRIES_SUCCESS';
export const ALLCOUNTRIES_ERROR = 'ALLCOUNTRIES_ERROR';
//Get Country States
export const COUNTRYSTATES_SUCCESS = 'COUNTRYSTATES_SUCCESS';
export const COUNTRYSTATES_ERROR = 'COUNTRYSTATES_ERROR';