//Users
//Get All Users
export const ALLUSERS_LOADING = 'ALLUSERS_LOADING';
export const ALLUSERS_SUCCESS = 'ALLUSERS_SUCCESS';
export const ALLUSERS_ERROR = 'ALLUSERS_ERROR';
//User Types
export const ALLUSERTYPES_SUCCESS = 'ALLUSERTYPES_SUCCESS';
export const ALLUSERTYPES_ERROR = 'ALLUSERTYPES_ERROR';
//Add User
export const ADDUSER_SUCCESS = 'ADDUSER_SUCCESS';
export const ADDUSER_ERROR = 'ADDUSER_ERROR';
//Remove User
export const REMOVEUSER_SUCCESS = 'REMOVEUSER_SUCCESS';
export const REMOVEUSER_ERROR = 'REMOVEUSER_ERROR';

//Teams
//Get All Teams
export const ALLTEAMS_LOADING = 'ALLTEAMS_LOADING';
export const ALLTEAMS_SUCCESS = 'ALLTEAMS_SUCCESS';
export const ALLTEAMS_ERROR = 'ALLTEAMS_ERROR';

//Match
//Get All Matches
export const ALLMATCHES_LOADING = 'ALLMATCHES_LOADING';
export const ALLMATCHES_SUCCESS = 'ALLMATCHES_SUCCESS';
export const ALLMATCHES_ERROR = 'ALLMATCHES_ERROR';

//Get All Countries
export const ALLCOUNTRIES_SUCCESS = 'ALLCOUNTRIES_SUCCESS';
export const ALLCOUNTRIES_ERROR = 'ALLCOUNTRIES_ERROR';
//Get Country States
export const COUNTRYSTATES_SUCCESS = 'COUNTRYSTATES_SUCCESS';
export const COUNTRYSTATES_ERROR = 'COUNTRYSTATES_ERROR';